spring.application.name=tenis_reservation_system

spring.datasource.url=jdbc:h2:mem:reservationdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always

jwt.secret=7f8c9b2a1e4d6f8a3c5e7b9d2f4a6c8e1b3d5f7a9c2e4b6d8f1a3c5e7b9d2f4a
jwt.access-expiration=3600000
#1 hodina
jwt.refresh-expiration=86400000
#24 hodin

app.initialization.enabled=true
#true/false mo?nosti