CREATE TABLE surfaces (
                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          name VARCHAR(255),
                          minute_rate INTEGER
);

CREATE TABLE courts (
                        id BIGINT AUTO_INCREMENT PRIMARY KEY,
                        name VARCHAR(255),
                        surface_id BIGINT,
                        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                        CONSTRAINT fk_court_surface FOREIGN KEY (surface_id) REFERENCES surfaces(id)
);

CREATE TABLE customers (
                           phone VARCHAR(50) PRIMARY KEY,
                           user_id BIGINT NOT NULL,
                           name VARCHAR(255) NOT NULL
);

CREATE TABLE reservations (
                              id BIGINT AUTO_INCREMENT PRIMARY KEY,
                              court_id BIGINT NOT NULL,
                              customer_phone VARCHAR(50) NOT NULL,
                              start_time TIMESTAMP NOT NULL,
                              end_time TIMESTAMP NOT NULL,
                              is_doubles BOOLEAN NOT NULL,
                              CONSTRAINT fk_reservation_court FOREIGN KEY (court_id) REFERENCES courts(id),
                              CONSTRAINT fk_reservation_customer FOREIGN KEY (customer_phone) REFERENCES customers(phone)
);

CREATE TABLE app_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           username VARCHAR(255) NOT NULL UNIQUE,
                           password VARCHAR(255) NOT NULL,
                           role VARCHAR(50) NOT NULL
);

INSERT INTO app_users (username, password, role) VALUES
                                                     ('admin', '$2a$12$Ufx7ZGr2XnogSoPW6yj4B.SZSsIrFzgfsovXAEguuSJpU2FQWNKXW', 'ADMIN'),
                                                     ('user', '$2a$12$RpSPCTzU7bdhfhUq006c2uQr.W3.gWERJSvsL6HT8JxgPQcOjW3RS', 'USER');
